### ISSUE TITLE
Typescript Go To Definition error

### ISSUE THREAD

**Issue by sijav** [rosieks/Rosieks.VisualStudio.Angular#3]
Hi another issue with this is that when I try to go to definition in any typescript files by pressing F12 on simple variables or functions or select it in menu I face an error message window with nothing but "KEY" written as the error's description and Error as the title.
And there's nothing in visual studio as log
Although peek definition is working (Alt+F12)

**Comment by rosieks** [comment]
Thanks for your feedback. This issue is fixed in version 0.5.8
